### PR TITLE
Modular

### LINKED ISSUE #4: Make sections modular
It doesn't make sense to keep everything a multi-thousand line tex file. Should be split into standalone files, ideally which can be compiled separately.

### LINKED ISSUE #19: makefile broken
#10 renamed `sols` target to `pdf` but didn't change in default target.

If I just type in make I get an error. Is this intended.

_Originally posted by @txa in https://github.com/txa/cftlfp/issues/4#issuecomment-2233073498_

### PR DESCRIPTION
**Pull request by jacobneu**
- Renamed `notes` to `CftLFP`
- Split file into individual chapters
- Changed from `article` to `book`, renamed sections to chapters, subsections to sections, etc.
- Moved macros into separate file

Closes #4 
Closes #19

### CODE REVIEW

**Comment by jacobneu** [comment]
https://github.com/txa/cftlfp/issues/4#issuecomment-2232761746

**Comment by jacobneu** [comment]
> [#4 (comment)](https://github.com/txa/cftlfp/issues/4#issuecomment-2232761746)

Should this be a separate chapter from preliminaries? As it is, preliminaries is rather short, so it would make sense to rename the first chapter to 'Introduction', and have preliminaries as a section.

**Comment by txa** [comment]
> > [#4 (comment)](https://github.com/txa/cftlfp/issues/4#issuecomment-2232761746)
> 
> Should this be a separate chapter from preliminaries? As it is, preliminaries is rather short, so it would make sense to rename the first chapter to 'Introduction', and have preliminaries as a section. The content of preliminaries would fit in well with the content described in #17, as far as I can tell.

Ok let's do that then.

**Comment by txa** [comment]
I still get an error if i just say make - is this intended?

**Comment by txa** [comment]
Ok, what is our policy? Shall I merge or leave it to you?

**Review by txa — APPROVED** [review]
Please merge when you are ready.

**Comment by jacobneu** [comment]
> Ok, what is our policy? Shall I merge or leave it to you?

I'll change the first chapter to 'Introduction' and then merge. In the future, I think we can just have the policy of merging it when both of us have had the chance to look at it (i.e. one of us creates the PR, the other approves the changes, and then the creator of the PR merges, like we've done here)

**Pull request merged**
